sudo: false
language: node_js
node_js:
        - "5"
install:
        - wget https://github.com/wsshin/jemdoc_mathjax/archive/master.tar.gz
        - tar -xvf master.tar.gz
        - export PATH=$PATH:$PWD/jemdoc_mathjax-master
script:
        - jemdoc *.jemdoc
